# Sample cheat sheet {#appendix-cheat-sheet}

As you make progress with Datacamp modules, 
you will learn an increasing number of new `R` functions, routines, etc. 
Before you realize it, the number will exceed what your memory can handle. 
This is when an external memory is needed: or what I call a *cheat sheet*. 

I suggest that you start with an empty file called `master-cheatsheet.R`. 
You can place the file inside one of the project folders 
that you created in Chapter \@ref(getting-started). 
From now on, 
whenever you encounter a new function or a new way of using a familiar function, 
I suggest that you write them down in the cheat sheet. 
~~I attach a snippet of a sample cheat sheet below for your reference. 
By no means do you have to use the same style.~~ 
I will periodically select a few cheat sheets from the class, 
take a snippet from each and post them here. 
Each one has some merits that are worth learning from for all of us. 

**TL;DR** 

+ A good example is worth a thousand lines of comments.
+ Be generous with spaces and empty lines to visually separate 
comments from code, and between code chunks.
+ Be stingy with special symbols such as `*`, `#`, `_`. 
  Avoid littering them all over the file.
+ Having too much information is as useless as having too little. 
  At some point, you have to be selective about what to include in your 
  cheat sheet. 
+ Inject structures into the file with headings of different levels.


## Sample cheat sheet 1

*`cheatsheet.txt`*

`r import_example('sample_cheatsheet.R')`

**Comments**: 

The author has excelled at both content and style of their cheat sheet. 
The whole file consists of numerous identically structured pieces. 
Each piece consists of the same components: purpose, commands, 
and an accompanying example. 
The comments are usually concise but with carefully chosen words. 
The usage of `#` is not excessive --- it is used to indicate 
non-code lines or the beginning of a piece. 
The double blank lines are used to separate any two adjacent pieces. 

Room for improvement: as the file length grows, some hierarchical structure 
may be helpful. See the next example (\@ref(sample-2)). 


## Sample cheat sheet 2 {#sample-2}

*`cheatsheet.Rmd`*


`r import_example('sample_cheatsheet.Rmd')`

When you compile the `Rmd` file using the "knit" button in RStudio, 
the output would look like this: 


```{r echo=F}
htmltools::tags$iframe(
                       src = file.path("examples/sample_cheatsheet.html"), 
                       width = "80%", 
                       height = "500", 
                       scrolling = "yes", 
                       frameborder = "1"
                       )
```

*Place your mouse cursor inside the box and try to scroll up and down 
to see the full sample.*

**Comments**:

The author took advantage of some nice features of `rmarkdown` 
and made their cheat sheet versatile. 
By setting `eval=F` in the first chunk (named "setup"), 
all the following `R` chunks would not be evaluated by default, 
suiting the design of a cheatsheet. 
However, whenever the author wants to show the output of a specific chunk, 
perhaps to remind themselves what the code does, 
they can turn on `eval=T` inside the header of a chunk, 
such as in the `demo-alpha` chunk. 
The author also structured the file with headings at different levels, 
using `##`, `###`, etc. 


## Feeling inspired?

Keep in mind that you will be working on YOUR cheat sheet 
and will refer to it from time to time 
as you learn to become a seasoned `R` user. 
Customize it. Own it. 
Put whatever content that is deemed useful to you. 
Each week, you will hand in an updated version of the **same** file ---
your cheat sheet, to fulfill the course requirement. 
I expect that everyone's cheat sheet will evolve over time. 
Your cheat sheet by the end of the first week 
may contain a line on how to examine the structure of a dataframe, for example; 
and by the end of the semester, 
you may know this line by heart and no longer need it on the cheat sheet. 

